#!/bin/bash

yes | pkg update -y &&
pkg upgrade -y;
echo "deb https://mirror.albony.xyz/termux/termux-main stable main" > $PREFIX/etc/apt/sources.list;
termux-setup-storage &&
pkg install git mpv -y;
# pip install yt-dlp;
cd $PREFIX && curl -LJOf https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.tar.gz && tar -xvf yt-dlp.tar.gz
echo 'export PATH="$PREFIX/yt-dlp:$PATH"' >> $PREFIX/etc/bash.bashrc
# cd storage && mkdir -p termux;
mkdir -p $HOME/storage/termux
#git clone https://github.com/Lavkush-Singh34/ytd-cli.git;
#chmod +x ./ytd-cli/yt;
#curl -JO https://raw.githubusercontent.com/Lavkush-Singh34/ytd-cli/main/yt -o $PREFIX/bin
curl -JO https://raw.githubusercontent.com/Lavkush-Singh34/ytd-cli/main/yt && chmod +x yt && mv yt $PREFIX/bin/
echo "Congratulations..!"

